Traceback (most recent call last):
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/ciaraacosta/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
simulated_stats = []

for i in range(5000):
    wages["shuffle"] = wages["hs degree"].sample(n=526, ignore_index=True)
    avg_wages = wages.groupby("shuffle").mean()["wage"]
    simulated_stats += [avg_wages[1] - avg_wages[0]]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-6ef4a9837437>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m5000[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mwages[0m[0;34m[[0m[0;34m"shuffle"[0m[0;34m][0m [0;34m=[0m [0mwages[0m[0;34m[[0m[0;34m"hs degree"[0m[0;34m][0m[0;34m.[0m[0msample[0m[0;34m([0m[0mn[0m[0;34m=[0m[0;36m526[0m[0;34m,[0m [0mignore_index[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m     [0mavg_wages[0m [0;34m=[0m [0mwages[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0;34m"shuffle"[0m[0;34m)[0m[0;34m.[0m[0mmean[0m[0;34m([0m[0;34m)[0m[0;34m[[0m[0;34m"wage"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m     [0msimulated_stats[0m [0;34m+=[0m [0;34m[[0m[0mavg_wages[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;34m-[0m [0mavg_wages[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: sample() got an unexpected keyword argument 'ignore_index'
TypeError: sample() got an unexpected keyword argument 'ignore_index'

